### ISSUE TITLE
License in composer.json is LGPL-3.0-or-later but MIT in other places

### ISSUE THREAD

**Issue by johanwilfer** [goetas-webservices/xsd2php-runtime#11]
I just noticed that composer.json states that the license is LGPL, but the license-file and the README states MIT. Can we change composer.json to say "MIT"?

**Comment by goetas** [comment]
This was a part left when moving from https://github.com/goetas/xsd2php, https://github.com/goetas-webservices/xsd2php-runtime/commit/eb91dac67160213589ecb8d36270e0a57cefc554 fixes it
