### ISSUE TITLE
Method serializeDateTime() trims dates with string "00:00"

### ISSUE THREAD

**Issue by carnau** [goetas-webservices/xsd2php-runtime#4]
Hello,

I found that the serializeDateTime method of the XmlSchemaDateHandler class, removes the substring "00:00" in case is present. Can you please explain the reason behind this?

Thank you

**Comment by goetas** [comment]
was done log time ago and should affect only the timezone... mainly because of http://books.xmlschemata.org/relaxng/ch19-77049.html where it says that is optional.

`[-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]`

`[Z|(+|-)hh:mm]`

If there are some problems, feel free to submit a PR

**Comment by carnau** [comment]
Yes, I'm using a system which requires to append it so I will make the PR as soon I have time.

Many thanks.

**Comment by goetas** [comment]
done https://github.com/goetas-webservices/xsd2php-runtime/issues/5
